on:
  release:
    types: [released]

name: Release image

jobs:
  release-image:
    name: Release image
    runs-on: ubuntu-latest

    steps:
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Get tag
        id: tag_name
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - name: Create alias
        run: docker tag ghcr.io/cpdt/mrvn-bot:${{ github.sha }} ghcr.io/cpdt/mrvn-bot:${{ steps.tag_name.outputs.name }}

      - name: Push alias
        run: docker push ghcr.io/cpdt/mrvn-bot:${{ steps.tag_name.outputs.name }}
